#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training2.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WelcomeLetter")]
	public partial class LettersContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LettersContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WelcomeLetterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LettersContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LettersContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LettersContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LettersContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LetterCriteria> LetterCriterias
		{
			get
			{
				return this.GetTable<LetterCriteria>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LetterCriteria")]
	public partial class LetterCriteria
	{
		
		private int _LetterId;
		
		private string _AccountType;
		
		private string _CoinsuranceAccountType;
		
		private string _MPInd;
		
		private string _facilityState;
		
		private string _FacilityNbr;
		
		private string _PatientNbr;
		
		private string _PatientsLastName;
		
		private string _PatientsFirstName;
		
		private System.Nullable<int> _DaysSinceAdmitDate;
		
		private string _ScheduledforPrinton;
		
		private string _CriteriaNoteMet;
		
		private string _ActiveFlag;
		
		private string _BSLorME;
		
		private string _AdditionalField;
		
		private string _LetterName;
		
		private string _IntakeResource;
		
		public LetterCriteria()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int LetterId
		{
			get
			{
				return this._LetterId;
			}
			set
			{
				if ((this._LetterId != value))
				{
					this._LetterId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountType", DbType="VarChar(50)")]
		public string AccountType
		{
			get
			{
				return this._AccountType;
			}
			set
			{
				if ((this._AccountType != value))
				{
					this._AccountType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoinsuranceAccountType", DbType="VarChar(50)")]
		public string CoinsuranceAccountType
		{
			get
			{
				return this._CoinsuranceAccountType;
			}
			set
			{
				if ((this._CoinsuranceAccountType != value))
				{
					this._CoinsuranceAccountType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPInd", DbType="VarChar(50)")]
		public string MPInd
		{
			get
			{
				return this._MPInd;
			}
			set
			{
				if ((this._MPInd != value))
				{
					this._MPInd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facilityState", DbType="VarChar(50)")]
		public string facilityState
		{
			get
			{
				return this._facilityState;
			}
			set
			{
				if ((this._facilityState != value))
				{
					this._facilityState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacilityNbr", DbType="VarChar(50)")]
		public string FacilityNbr
		{
			get
			{
				return this._FacilityNbr;
			}
			set
			{
				if ((this._FacilityNbr != value))
				{
					this._FacilityNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNbr", DbType="VarChar(50)")]
		public string PatientNbr
		{
			get
			{
				return this._PatientNbr;
			}
			set
			{
				if ((this._PatientNbr != value))
				{
					this._PatientNbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientsLastName", DbType="VarChar(50)")]
		public string PatientsLastName
		{
			get
			{
				return this._PatientsLastName;
			}
			set
			{
				if ((this._PatientsLastName != value))
				{
					this._PatientsLastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientsFirstName", DbType="VarChar(50)")]
		public string PatientsFirstName
		{
			get
			{
				return this._PatientsFirstName;
			}
			set
			{
				if ((this._PatientsFirstName != value))
				{
					this._PatientsFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysSinceAdmitDate", DbType="Int")]
		public System.Nullable<int> DaysSinceAdmitDate
		{
			get
			{
				return this._DaysSinceAdmitDate;
			}
			set
			{
				if ((this._DaysSinceAdmitDate != value))
				{
					this._DaysSinceAdmitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduledforPrinton", DbType="VarChar(50)")]
		public string ScheduledforPrinton
		{
			get
			{
				return this._ScheduledforPrinton;
			}
			set
			{
				if ((this._ScheduledforPrinton != value))
				{
					this._ScheduledforPrinton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriteriaNoteMet", DbType="VarChar(255)")]
		public string CriteriaNoteMet
		{
			get
			{
				return this._CriteriaNoteMet;
			}
			set
			{
				if ((this._CriteriaNoteMet != value))
				{
					this._CriteriaNoteMet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveFlag", DbType="VarChar(1)")]
		public string ActiveFlag
		{
			get
			{
				return this._ActiveFlag;
			}
			set
			{
				if ((this._ActiveFlag != value))
				{
					this._ActiveFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSLorME", DbType="VarChar(50)")]
		public string BSLorME
		{
			get
			{
				return this._BSLorME;
			}
			set
			{
				if ((this._BSLorME != value))
				{
					this._BSLorME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalField", DbType="VarChar(50)")]
		public string AdditionalField
		{
			get
			{
				return this._AdditionalField;
			}
			set
			{
				if ((this._AdditionalField != value))
				{
					this._AdditionalField = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterName", DbType="VarChar(50)")]
		public string LetterName
		{
			get
			{
				return this._LetterName;
			}
			set
			{
				if ((this._LetterName != value))
				{
					this._LetterName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntakeResource", DbType="VarChar(50)")]
		public string IntakeResource
		{
			get
			{
				return this._IntakeResource;
			}
			set
			{
				if ((this._IntakeResource != value))
				{
					this._IntakeResource = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
